using DotnetTokenKiller.Application.Integration;
using FluentAssertions;

namespace DotnetTokenKiller.Application.Tests.Integration;

public sealed class PiExtensionTests
{
    [Theory]
    [InlineData("pi", "pi")]
    [InlineData("oh-my-pi", "oh-my-pi")]
    public void Body_KeepsTheContractBothHarnessesNeed(string provider, string harness)
    {
        var body = PiExtension.Body(provider, harness);

        body.Should().StartWith($"// dtk (DotnetTokenKiller) rewrites the dotnet commands dtk supports to `dtk dotnet ...` before {harness} runs them.\n");
        body.Should().Contain($"Generated by `dtk init {provider}`");
        body.Should().Contain("spawn(dtk, " + PluginRuntime.InvocationSignature(provider))
            .And.NotContain("spawn(\"dtk\"").And.NotContain("shell: true");
        body.Should().Contain("pi.on(\"tool_call\"").And.Contain("event?.toolName !== \"bash\"").And.Contain("command.includes(\"dotnet\")");
        body.Should().Contain("input.command = rewritten;", "pi executes the args object it passed in");
        body.Should().Contain("return { input: { ...input, command: rewritten } };", "oh-my-pi executes the returned input");
        body.Split("export ").Should().HaveCount(2).And.Subject.Last().Should().StartWith("default function (pi)");
        body.Should().NotContain("@earendil-works").And.NotContain("@mariozechner").And.NotContain("@oh-my-pi");
    }

    [Fact]
    public void Artifact_IsStampedWithSlashComments()
    {
        var artifact = PiExtension.Artifact("/x/dtk.js", "pi", "pi");

        artifact.Style.Should().Be(StampStyle.SlashComment);
        artifact.Body.Should().Be(PiExtension.Body("pi", "pi"));
        artifact.LegacySignature.Should().Be(ArtifactStamping.StampPrefix, "no dtk ever wrote an unstamped extension");
    }
}
