namespace DotnetTokenKiller.Application.Integration;

/// <summary>The plugin <c>dtk init amp</c> generates.</summary>
/// <remarks>
/// <para>
/// Amp loads <c>export default function (amp)</c> plugins from <c>.amp/plugins/</c> and the user's config directory and
/// fires <c>tool.call</c> before a tool runs. For a shell call (Amp's own <c>shellCommandFromToolCall</c> helper decides
/// which calls those are) whose command contains <c>dotnet</c>, the plugin asks <c>dtk hook amp</c> through
/// <see cref="PluginRuntime"/> and returns <c>{ action: "modify" }</c> with the rewritten command in whichever input
/// field held it (<c>cmd</c> or <c>command</c>), so the tool's other arguments are untouched.
/// </para>
/// <para>
/// Amp requires every <c>tool.call</c> handler to return a result, and a throw or an <c>error</c> result stops the
/// thread, so every other path — another tool, no dotnet, no dtk, a slow or malformed reply — returns
/// <c>{ action: "allow" }</c>.
/// </para>
/// </remarks>
internal static class AmpPlugin
{
    /// <summary>The call a plugin still runs dtk through, even after local edits.</summary>
    internal static readonly string InvocationSignature = PluginRuntime.InvocationSignature("amp");

    /// <summary>The plugin source, before stamping.</summary>
    internal static readonly string Body =
        $$"""
        // dtk (DotnetTokenKiller) rewrites the dotnet commands dtk supports to `dtk dotnet ...` before Amp runs them.
        // Generated by `dtk init amp`; run it again to refresh this file.
        {{PluginRuntime.Source("amp", "Amp")}}
        const ALLOW = { action: "allow" };

        export default function (amp) {
          amp.on("tool.call", async (event) => {
            try {
              const input = event?.input;
              const command = amp?.helpers?.shellCommandFromToolCall?.(event)?.command;
              if (typeof command !== "string" || !command.includes("dotnet") || input === null || typeof input !== "object") return ALLOW;
              const field = ["cmd", "command"].find((key) => input[key] === command);
              if (field === undefined) return ALLOW;
              const rewritten = await rewrite(command);
              if (typeof rewritten !== "string" || rewritten === "" || rewritten === command) return ALLOW;
              return { action: "modify", input: { ...input, [field]: rewritten } };
            } catch {
              // A throw would stop Amp's thread.
              return ALLOW;
            }
          });
        }

        """;

    /// <summary>The plugin as a generated artifact at <paramref name="path"/>.</summary>
    /// <param name="path">Where the plugin is written.</param>
    internal static GeneratedArtifact Artifact(string path) =>
        new(path, Body, StampStyle.SlashComment, ArtifactStamping.StampPrefix);
}
