namespace DotnetTokenKiller.Application.Integration;

/// <summary>The OpenCode plugin <c>dtk init opencode</c> generates.</summary>
/// <remarks>
/// <para>
/// OpenCode runs no hook commands, only in-process plugins, so this plugin is the hook: for a <c>bash</c> tool call
/// whose command contains <c>dotnet</c>, it runs <c>dtk hook opencode</c> and writes the reply into
/// <c>output.args.command</c>. The rewrite itself stays in <c>DotnetCommandRewriter</c>.
/// </para>
/// <para>
/// Every line answers a known failure: <c>includes("dotnet")</c> is a superset of what the rewriter matches, so only
/// dotnet commands pay a process start; a throw would fail the tool call, so every path resolves to "no rewrite";
/// OpenCode passes the same <c>args</c> object on to the tool, so the command is changed in place and never replaced;
/// Bun's <c>$</c> is undefined when OpenCode runs on Node (Desktop) and <c>which</c> does not exist on Windows, so the
/// plugin uses <c>spawn</c> without a shell, which on Windows finds <c>dtk.exe</c>; and OpenCode v1 silently drops a
/// plugin with any non-function export.
/// </para>
/// </remarks>
internal static class OpenCodePlugin
{
    /// <summary>The call a plugin still runs dtk through, even after local edits.</summary>
    internal const string InvocationSignature = "spawn(\"dtk\", [\"hook\", \"opencode\"]";

    /// <summary>The plugin source, before stamping.</summary>
    internal const string Body =
        """
        // dtk (DotnetTokenKiller) rewrites the dotnet commands dtk supports to `dtk dotnet ...` before OpenCode runs them.
        // Generated by `dtk init opencode`; run it again to refresh this file.
        import { spawn } from "node:child_process";

        const TIMEOUT_MS = 5000;

        function rewrite(command) {
          return new Promise((resolve) => {
            let child;
            try {
              child = spawn("dtk", ["hook", "opencode"], { stdio: ["pipe", "pipe", "ignore"], windowsHide: true });
            } catch {
              resolve(null);
              return;
            }

            const chunks = [];
            const timer = setTimeout(() => {
              child.kill();
              resolve(null);
            }, TIMEOUT_MS);

            child.on("error", () => {
              clearTimeout(timer);
              resolve(null);
            });
            child.stdout.on("data", (chunk) => chunks.push(chunk));
            child.on("close", () => {
              clearTimeout(timer);
              try {
                resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")).command ?? null);
              } catch {
                resolve(null);
              }
            });
            child.stdin.on("error", () => {});
            child.stdin.end(JSON.stringify({ command }));
          });
        }

        export const DtkPlugin = async () => ({
          "tool.execute.before": async (input, output) => {
            try {
              if (input?.tool !== "bash") return;
              const command = output?.args?.command;
              if (typeof command !== "string" || !command.includes("dotnet")) return;
              const rewritten = await rewrite(command);
              if (typeof rewritten === "string" && rewritten !== "") output.args.command = rewritten;
            } catch {
              // A failed rewrite must never block the tool call.
            }
          },
        });

        """;

    /// <summary>The plugin as a generated artifact at <paramref name="path"/>.</summary>
    /// <param name="path">Where the plugin is written.</param>
    internal static GeneratedArtifact Artifact(string path) =>
        // No dtk ever wrote an unstamped dtk.js, so there is no legacy copy to migrate without --force; the
        // spec requires a user-edited plugin to be left alone. Passing the stamp's own prefix as the legacy
        // signature makes WriteGeneratedFileAsync's legacy branch permanently unreachable, since HasStamp is
        // exactly `content.Contains(StampPrefix)`.
        new(path, Body, StampStyle.SlashComment, ArtifactStamping.StampPrefix);
}
