namespace DotnetTokenKiller.Application.Integration;

/// <summary>The OpenCode plugin <c>dtk init opencode</c> generates.</summary>
/// <remarks>
/// <para>
/// OpenCode runs no hook commands, only in-process plugins, so this plugin is the hook: for a <c>bash</c> tool call
/// whose command contains <c>dotnet</c>, it runs <c>dtk hook opencode</c> and writes the reply into
/// <c>output.args.command</c>. The rewrite itself stays in <c>DotnetCommandRewriter</c>.
/// </para>
/// <para>
/// Every line answers a known failure: <c>includes("dotnet")</c> is a superset of what the rewriter matches, so only
/// dotnet commands pay a process start; a throw would fail the tool call, so every path resolves to "no rewrite";
/// OpenCode passes the same <c>args</c> object on to the tool, so the command is changed in place and never replaced;
/// Bun's <c>$</c> is undefined when OpenCode runs on Node (Desktop) and <c>which</c> does not exist on Windows, so the
/// plugin uses <c>spawn</c> without a shell; and OpenCode v1 silently drops a plugin with any non-function export.
/// </para>
/// <para>
/// The plugin resolves <c>dtk</c> from <c>PATH</c> itself and spawns the absolute path. Given a bare name on Windows,
/// libuv (Node) and Bun look in the current directory before <c>PATH</c>; OpenCode's current directory is the project,
/// and the plugin runs before OpenCode's permission check, so a <c>dtk.exe</c> committed to a repository would
/// otherwise run unapproved. Empty and relative <c>PATH</c> entries are skipped for the same reason, and off Windows a
/// candidate must be executable, as a shell requires. No <c>dtk</c> on <c>PATH</c> means no process and no rewrite.
/// </para>
/// </remarks>
internal static class OpenCodePlugin
{
    /// <summary>The call a plugin still runs dtk through, even after local edits.</summary>
    internal static readonly string InvocationSignature = PluginRuntime.InvocationSignature("opencode");

    /// <summary>The plugin source, before stamping.</summary>
    internal static readonly string Body =
        $$"""
        // dtk (DotnetTokenKiller) rewrites the dotnet commands dtk supports to `dtk dotnet ...` before OpenCode runs them.
        // Generated by `dtk init opencode`; run it again to refresh this file.
        {{PluginRuntime.Source("opencode", "OpenCode")}}
        export const DtkPlugin = async () => ({
          "tool.execute.before": async (input, output) => {
            try {
              if (input?.tool !== "bash") return;
              const command = output?.args?.command;
              if (typeof command !== "string" || !command.includes("dotnet")) return;
              const rewritten = await rewrite(command);
              if (typeof rewritten === "string" && rewritten !== "") output.args.command = rewritten;
            } catch {
              // A failed rewrite must never block the tool call.
            }
          },
        });

        """;

    /// <summary>The plugin as a generated artifact at <paramref name="path"/>.</summary>
    /// <param name="path">Where the plugin is written.</param>
    internal static GeneratedArtifact Artifact(string path) =>
        // No dtk ever wrote an unstamped dtk.js, so there is no legacy copy to migrate without --force; the
        // spec requires a user-edited plugin to be left alone. Passing the stamp's own prefix as the legacy
        // signature makes WriteGeneratedFileAsync's legacy branch permanently unreachable, since HasStamp is
        // exactly `content.Contains(StampPrefix)`.
        new(path, Body, StampStyle.SlashComment, ArtifactStamping.StampPrefix);
}
