namespace DotnetTokenKiller.Application.Integration;

/// <summary>The extension <c>dtk init pi</c> and <c>dtk init oh-my-pi</c> generate.</summary>
/// <remarks>
/// <para>
/// Both harnesses load <c>export default function (pi)</c> modules from their extensions directories and fire
/// <c>tool_call</c> before a tool runs. For a <c>bash</c> call whose command contains <c>dotnet</c>, the extension runs
/// <c>dtk hook &lt;provider&gt;</c> through <see cref="PluginRuntime"/> and applies the reply both ways, because the
/// two harnesses disagree on how a handler changes the input: pi passes the tool's own args object and ignores every
/// returned field but <c>block</c>, so the command is mutated in place; oh-my-pi passes a normalized copy and executes
/// the returned <c>input</c> (18.2.1 and later), so the full input is returned with the new command. Each harness
/// ignores the other's convention.
/// </para>
/// <para>
/// In both, a throwing handler blocks the tool call, so every path resolves to "no rewrite". The file imports neither
/// harness package, so it loads under either package name and under plain Node in tests.
/// </para>
/// </remarks>
internal static class PiExtension
{
    /// <summary>The extension source, before stamping.</summary>
    /// <param name="provider">The <c>dtk init</c>/<c>dtk hook</c> provider name.</param>
    /// <param name="harness">The harness's display name.</param>
    internal static string Body(string provider, string harness) =>
        $$"""
        // dtk (DotnetTokenKiller) rewrites the dotnet commands dtk supports to `dtk dotnet ...` before {{harness}} runs them.
        // Generated by `dtk init {{provider}}`; run it again to refresh this file.
        {{PluginRuntime.Source(provider, harness)}}
        export default function (pi) {
          pi.on("tool_call", async (event) => {
            try {
              if (event?.toolName !== "bash") return undefined;
              const input = event.input;
              const command = input?.command;
              if (typeof command !== "string" || !command.includes("dotnet")) return undefined;
              const rewritten = await rewrite(command);
              if (typeof rewritten !== "string" || rewritten === "") return undefined;
              // pi runs the args object it passed in; oh-my-pi passes a copy and runs the input a handler returns.
              input.command = rewritten;
              return { input: { ...input, command: rewritten } };
            } catch {
              // A throw would block the tool call.
              return undefined;
            }
          });
        }

        """;

    /// <summary>The extension as a generated artifact at <paramref name="path"/>.</summary>
    /// <param name="path">Where the extension is written.</param>
    /// <param name="provider">The provider name.</param>
    /// <param name="harness">The harness's display name.</param>
    internal static GeneratedArtifact Artifact(string path, string provider, string harness) =>
        // No dtk ever wrote an unstamped copy; the stamp prefix as legacy signature keeps the legacy branch unreachable,
        // exactly as for OpenCodePlugin.Artifact.
        new(path, Body(provider, harness), StampStyle.SlashComment, ArtifactStamping.StampPrefix);
}
