using DotnetTokenKiller.Application.Integration.Hooks;
using FluentAssertions;

namespace DotnetTokenKiller.Application.Tests.Integration.Hooks;

public sealed class DotnetCommandRewriterTests
{
    [Theory]
    [InlineData("dotnet build", "dtk dotnet build")]
    [InlineData("dotnet test", "dtk dotnet test")]
    [InlineData("dotnet restore", "dtk dotnet restore")]
    [InlineData("dotnet clean", "dtk dotnet clean")]
    [InlineData("dotnet format", "dtk dotnet format")]
    [InlineData("dotnet list package", "dtk dotnet list package")]
    [InlineData("dotnet list package --outdated", "dtk dotnet list package --outdated")]
    [InlineData("dotnet list   package", "dtk dotnet list   package")]
    [InlineData("dotnet   build", "dtk dotnet build")]
    [InlineData("dotnet\tformat", "dtk dotnet format")]
    [InlineData("cd src && dotnet test", "cd src && dtk dotnet test")]
    [InlineData("`dotnet build`", "`dtk dotnet build`")]
    [InlineData("echo dtk; dotnet build", "echo dtk; dtk dotnet build")]
    [InlineData("cd /tmp/dtk && dotnet test", "cd /tmp/dtk && dtk dotnet test")]
    [InlineData("(dotnet build)", "(dtk dotnet build)")]
    [InlineData("$(dotnet build)", "$(dtk dotnet build)")]
    [InlineData("{ dotnet build; }", "{ dtk dotnet build; }")]
    [InlineData("dotnet build\ndotnet test", "dtk dotnet build\ndtk dotnet test")]
    [InlineData("dotnet build && dotnet test", "dtk dotnet build && dtk dotnet test")]
    [InlineData("echo \u00e9 && dotnet build", "echo \u00e9 && dtk dotnet build")]
    [InlineData("echo \"a\\\" b\"; dotnet build", "echo \"a\\\" b\"; dtk dotnet build")]
    [InlineData("x=1 dotnet build", "x=1 dtk dotnet build")]
    [InlineData("sudo dotnet build", "sudo dtk dotnet build")]
    [InlineData("DTK dotnet build", "DTK dtk dotnet build")]
    [InlineData("dtk.EXE dotnet build", "dtk.EXE dtk dotnet build")]
    [InlineData("dotnet build-server shutdown", "dtk dotnet build-server shutdown")]
    [InlineData("out=\"$(dotnet build 2>&1)\"", "out=\"$(dtk dotnet build 2>&1)\"")]
    [InlineData("echo \"$(echo \"$(dotnet test)\")\"", "echo \"$(echo \"$(dtk dotnet test)\")\"")]
    [InlineData("echo \"`dotnet build`\"", "echo \"`dtk dotnet build`\"")]
    [InlineData("dotnet build '$(x)'", "dtk dotnet build '$(x)'")]
    [InlineData("echo 1 # it's fine\ndotnet build", "echo 1 # it's fine\ndtk dotnet build")]
    [InlineData("cat <<EOF\ndotnet build\nEOF\ndotnet build", "cat <<EOF\ndotnet build\nEOF\ndtk dotnet build")]
    [InlineData("cat <<-EOF\n\tdotnet build\n\tEOF\ndotnet test", "cat <<-EOF\n\tdotnet build\n\tEOF\ndtk dotnet test")]
    [InlineData("cat <<'A' <<B\ndotnet build\nA\ndotnet test\nB\ndotnet clean", "cat <<'A' <<B\ndotnet build\nA\ndotnet test\nB\ndtk dotnet clean")]
    [InlineData("dotnet build <<EOF\nx\nEOF", "dtk dotnet build <<EOF\nx\nEOF")]
    [InlineData("cat <<< x; dotnet build", "cat <<< x; dtk dotnet build")]
    [InlineData("echo a#b; dotnet build", "echo a#b; dtk dotnet build")]
    [InlineData("echo $'it\\'s'; dotnet build", "echo $'it\\'s'; dtk dotnet build")]
    [InlineData("echo $$'\\'; dotnet build", "echo $$'\\'; dtk dotnet build")]
    [InlineData("x=$$'\\'; dotnet build #'", "x=$$'\\'; dtk dotnet build #'")]
    [InlineData("echo \"$$\"; dotnet build", "echo \"$$\"; dtk dotnet build")]
    [InlineData("echo $\"it's\"; dotnet build", "echo $\"it's\"; dtk dotnet build")]
    [InlineData("dtk\ndotnet build", "dtk\ndtk dotnet build")]
    [InlineData("dotnet list\tpackage", "dtk dotnet list\tpackage")]
    [InlineData("! dotnet build", "! dtk dotnet build")]
    [InlineData("echo \"hi!\"; dotnet build $[1]", "echo \"hi!\"; dtk dotnet build $[1]")]
    public void Rewrite_QualifyingInvocation_IsPrefixedWithDtk(string command, string expected)
    {
        DotnetCommandRewriter.Rewrite(command).Should().Be(expected);
    }

    [Theory]
    [InlineData("/usr/lib64/dotnet/dotnet build")]
    [InlineData("./dotnet build")]
    [InlineData("mydotnet build")]
    [InlineData("DOTNET build")]
    [InlineData("dotnet tests")]
    [InlineData("dotnet build_x")]
    [InlineData("dotnet build\u00e9")]
    [InlineData("dotnet build\u00b2")]
    [InlineData("dotnet publish")]
    [InlineData("dotnet --info")]
    [InlineData("dotnet list  reference")]
    [InlineData("git commit -m \"fix dotnet build\"")]
    [InlineData("echo 'dotnet test'")]
    [InlineData("echo 'it\\'s'; dotnet build")]
    [InlineData("`dtk dotnet build`")]
    [InlineData("(dtk dotnet build)")]
    [InlineData("$(dtk dotnet build)")]
    [InlineData("echo hi;dtk dotnet build")]
    [InlineData("true&&dtk dotnet test")]
    [InlineData("ls|dtk dotnet format")]
    [InlineData("dtk  dotnet build")]
    [InlineData("~/.dotnet/tools/dtk dotnet build")]
    [InlineData(@"C:\tools\dtk.exe dotnet restore")]
    [InlineData("")]
    [InlineData("cat > s.sh <<'EOF'\ndotnet build\nEOF")]
    [InlineData("cat > s.sh <<\"EOF\"\ndotnet build\nEOF")]
    [InlineData("cat > s.sh <<EOF\ndotnet build\nEOF")]
    [InlineData("cat > s.sh <<-EOF\n\tdotnet build\n\tEOF")]
    [InlineData("cat <<EOF\ndotnet build")]
    [InlineData("echo 1 # dotnet build")]
    [InlineData("echo \"\\$(dotnet build)\"")]
    [InlineData("echo '$(dotnet build)'")]
    [InlineData("\"$(dtk dotnet build)\"")]
    [InlineData("dotnet\nbuild")]
    [InlineData("dotnet\r\nbuild")]
    [InlineData("dotnet\u00a0build")]
    [InlineData("dotnet\vbuild")]
    [InlineData("dotnet\fbuild")]
    [InlineData("dotnet\u2028build")]
    [InlineData("dotnet list\u00a0package")]
    [InlineData("dotnet list\npackage")]
    [InlineData("cat <<EOF; dotnet\nbuild\nEOF")]
    public void Rewrite_NonQualifyingInvocation_IsReturnedUnchanged(string command)
    {
        DotnetCommandRewriter.Rewrite(command).Should().BeSameAs(command);
    }

    [Theory]
    [InlineData("dotnet build", true)]
    [InlineData("dotnet test --filter \"A|B\"", true)]
    [InlineData("dotnet test --filter 'A&B'", true)]
    [InlineData("echo \\; dotnet build", false)]
    [InlineData("dotnet build && rm -rf x", false)]
    [InlineData("dotnet build; ls", false)]
    [InlineData("dotnet build | tee log", false)]
    [InlineData("$(dotnet build)", false)]
    [InlineData("dotnet build\nls", false)]
    [InlineData("dotnet build 2>&1", false)]
    [InlineData("dotnet build \"$(rm -rf ~)\"", false)]
    [InlineData("dotnet build \"`id`\"", false)]
    [InlineData("dotnet build `id`", false)]
    [InlineData("dotnet build $(id)", false)]
    [InlineData("dotnet build \"$((1+2))\"", false)]
    [InlineData("echo \"$(echo \"$(dotnet test)\")\"", false)]
    [InlineData("dotnet build '$(x)'", true)]
    [InlineData("dotnet build '`id`'", true)]
    [InlineData("dotnet build \"\\$(x)\"", true)]
    [InlineData("dotnet build \\$\\(x\\)", true)]
    [InlineData("dotnet build \\; x", true)]
    [InlineData(" \tdotnet build $$ \"$HOME\" {a,b}", true)]
    [InlineData("dotnet build \"a;b\" # c; d", false)]
    [InlineData("dotnet build $$'\\'; rm -rf ~ #'", false)]
    [InlineData("dotnet build \"$$(id)\"", true)]
    [InlineData("rm -rf ~ dotnet build", false)]
    [InlineData("sudo dotnet build", false)]
    [InlineData("x=1 dotnet build", false)]
    [InlineData("dotnetx build", false)]
    [InlineData("dotnet", false)]
    [InlineData("dotnet build > ~/.bashrc", false)]
    [InlineData("dotnet build < input", false)]
    [InlineData("dotnet build $'a'", false)]
    [InlineData("dotnet build $\"a\"", false)]
    [InlineData("dotnet build ${x}", false)]
    [InlineData("dotnet build \"${x/'\"'/y}\"", false)]
    [InlineData("dotnet build # c", false)]
    [InlineData("dotnet build \"!#;echo PWNED;#\"", false)]
    [InlineData("dotnet build !!", false)]
    [InlineData("dotnet build \"hi!\"", false)]
    [InlineData("dotnet build '!x'", true)]
    [InlineData("dotnet build \\!x", true)]
    [InlineData("dotnet build $[HOME]", false)]
    [InlineData("dotnet build \"$[HOME]\"", false)]
    [InlineData("dotnet build '$[HOME]'", true)]
    [InlineData("dotnet build # c\nls", false)]
    [InlineData("dotnet build a\\ #; rm -rf ~", false)]
    [InlineData("dotnet build a#; rm -rf ~", false)]
    [InlineData("dotnet build $'\\''; rm -rf ~", false)]
    [InlineData("dotnet build <<EOF", false)]
    [InlineData("cat <<'EOF'\nx\nEOF", false)]
    [InlineData("dotnet build \"unterminated", false)]
    [InlineData("dotnet build 'unterminated", false)]
    public void IsSimpleCommand_OnlyAcceptsASingleInvocation(string command, bool expected)
    {
        DotnetCommandRewriter.IsSimpleCommand(command).Should().Be(expected);
    }
}
