<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DotnetTokenKiller.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DotnetTokenKiller.Domain/DotnetTokenKiller.Domain.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DotnetTokenKiller.Infrastructure.Tests"/>
  </ItemGroup>
</Project>
